#:kivy 1.10.0
#:import SwapTransition kivy.uix.screenmanager.SwapTransition

<MyScreenManager>:
    transition: SwapTransition()
    Registers:
        on_enter:
            self.add_buttons()
        on_leave:
            self.remove_buttons()
    Welcome:

<Login>:
    id: login
    name: "login"
    login: login
    GridLayout:
        size_hint: (0.5, 0.5)
        pos_hint: {"center_x": 0.5, "center_y": 0.6}
        rows: 3
        padding: 20

        Label:
            size_hint: (0.2, 0.2)
            text:"Password:"
            font_size: 30
            halign: "center"
            valign: "middle"

        TextInput:
            id: password
            size_hint: (0.2, 0.06)
            cursor_blink: True
            font_size: 20
            multiline: False
            password: True

        Button:
            text: "Continue"
            size_hint: (0.2, 0.08)
            on_release:
                root.login.check_password(root.manager, password.text)

<Registers>:
    name:'registers'
    container: btn_a

    BoxLayout:
        id: bl
        orientation: 'vertical'
        padding: 50, 40
        row_default_height: '48dp'
        row_force_default: True
        spacing: 10, 10
        Button:
            text: 'Next Screen'
            on_press: root.manager.current = 'welcome'
            height: 10

        ScrollView:
            size: self.size
            GridLayout:
                id: btn_a
                size_hint_y: None
                cols: 1
                row_default_height: '20dp'
                row_force_default: True
                spacing: 0, 5
                padding: 0, 0
                height: self.minimum_height
                                

<Welcome>:
    name:'welcome'
    BoxLayout:
        Label:
            text: 'Welcome!'
        Button:
            text: 'Return to Registers'
            on_press:
                root.manager.current = 'registers'