language: python
python: 3.7

matrix:
  include:
  - name: "Python"
    os: windows           
    language: shell       
    before_install:
     - choco install python --version 3.7
     - python --version
     - python -m pip install --upgrade pip
     - pip3 install --upgrade pytest
    env: PATH=/c/Python35:/c/Python35/Scripts:$PATH