matrix:
  include:
    - name: "PythonWindows"
      os: windows          
      language: shell      
      before_install:
        - choco install python3 --version 3.7
      install:
       py -m pip install -r travisRequirements
      script: py -m pytest
    - name: "Python 2.7.14 on macOS 10.13"
      os: osx
      osx_image: xcode9.3  
      language: shell  
      before_install:
        - python --version
        - pip install pytest --user
      script: python -m pytest  