language: python
python: 3.7

matrix:
  include:
  - os: windows
    language: shell
    python: "3.7"
    before_install: 
      - choco install python --version 3.7

    install:
      - python3 -m pip install -r requirements.txt

  - os: osx
    langauge: shell
script:
  - python3 -m pytest
