language: python
python: 3.7

matrix:
  include:
  - os: windows
    language: shell
    python: "3.7"
    before_install: 
      - choco install python3
      - python -m pip install --upgrade pytest
      - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    install:
      - pip3 install -r requirements.txt

  - os: osx
    langauge: shell
script:
  - pytest
