language: python
python: 3.7

matrix:
  include:
  - os: windows
    language: shell
    python: "3.7"
    before_install: 
      - choco install python3
      -python -m pip install -U pip
      - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    install:
      - python -m pip install -r requirements.txt
    
  - os: osx
    langauge: shell
script:
  - pytest
