matrix:
  include:
    - name: "PythonWindows"
      os: windows          
      language: shell      
      before_install:
        - choco install python3 --version 3.7
        - py -m pip install --upgrade pip
      install:
       py -m pip install -r travisRequirements.txt
      script: py -m pytest
    - name: "Python"
      os: osx
      osx_image: xcode9.3  
      language: shell  
      before_install:
        - python --version 3.7
        - pip install pytest --user
        - pip install --upgrade pip
        - pip install -r travisRequirements.txt
      script: python -m pytest  